<?php
require_once 'header.php';
snmp_set_valueretrieval(SNMP_VALUE_PLAIN);
$ip = "127.0.0.1";
echo '<link rel="stylesheet" href="../css/p3.css">';
?>

<div class="page">
<div class="section">
<div class="section-title">Method 1 : snmp2_get()</div>
<table>
<tr>
    <th>Number</th>
    <th>OID</th>
    <th>Name</th>
    <th>Description</th>
    <th>Value</th>
</tr>
<?php
$data = [
1=>["InPkts","The total number of Messages delivered to the SNMP entity from the transport service."],2=>["OutPkts","The total number of SNMP Messages which were passed from the SNMP protocol entity to the transport service."],3=>["BadVersions","The total number of SNMP Messages which were delivered to the SNMP protocol entity and were for an unsupported SNMP version."],4=>["BadCommNames","	
The total number of SNMP Messages delivered to the SNMP protocol entity which used a SNMP community name not known to said entity."],
5=>["BadCommUses","The total number of SNMP Messages delivered to the SNMP protocol entity which represented an SNMP operation which was not allowed by the SNMP community named in the Message."],6=>["snmpInASNParseErrs","The total number of ASN.1 or BER errors encountered by the SNMP protocol entity when decoding received SNMP Messages."],8=>["snmpInTooBigs","The total number of SNMP PDUs which were delivered to the SNMP protocol entity and for which the value of the error-status field is tooBig."],9=>["snmpInNoSuchNames","	
The total number of SNMP PDUs which were delivered to the SNMP protocol entity and for which the value of the error-status field is noSuchName."],
10=>["snmpInBadValues","The total number of SNMP PDUs which were delivered to the SNMP protocol entity and for which the value of the error-status field is badValue."],
11=>["snmpInReadOnlys","The total number valid SNMP PDUs which were delivered to the SNMP protocol entity and for which the value of the error-status field is readOnly."],
12=>["snmpInGenErrs","The total number of SNMP PDUs which were delivered to the SNMP protocol entity and for which the value of the error-status field is genErr."],
13=>["snmpInTotalReqVars","The total number of MIB objects which have been retrieved successfully by the SNMP protocol entity as the result of receiving valid SNMP Get-Request and Get-Next PDUs."],
14=>["snmpInTotalSetVars","The total number of MIB objects which have been altered successfully by the SNMP protocol entity as the result of receiving valid SNMP Set-Request PDUs."],
15=>["snmpInGetRequests","The total number of SNMP Get-Request PDUs which have been accepted and processed by the SNMP protocol entity"],
16=>["snmpInGetNexts","The total number of SNMP Get-Next PDUs which have been accepted and processed by the SNMP protocol entity"],
17=>["snmpInSetRequests","The total number of SNMP Set-Request PDUs which have been accepted and processed by the SNMP protocol entity"],
18=>["snmpInGetResponses","The total number of SNMP Trap PDUs which have been accepted and processed by the SNMP protocol entity."],
19=>["snmpInTraps","The total number of SNMP Trap PDUs which have been accepted and processed by the SNMP protocol entity."],
20=>["snmpOutTooBigs","The total number of SNMP PDUs which were generated by the SNMP protocol entity and for which the value of the error-status field is tooBig."],
21=>["snmpOutNoSuchNames","The total number of SNMP PDUs which were generated by the SNMP protocol entity and for which the value of the error-status is noSuchName."],
22=>["snmpOutBadValues","The total number of SNMP PDUs which were generated by the SNMP protocol entity and for which the value of the error-status field is badValue."],
24=>["snmpOutGenErrs","	The total number of SNMP PDUs which were generated by the SNMP protocol entity and for which the value of the error-status field is genErr."],
25=>["snmpOutGetRequests","The total number of SNMP Get-Request PDUs."],
26=>["snmpOutGetNexts","The total number of SNMP Get-Next PDUs."],
27=>["snmpOutSetRequests","The total number of SNMP Set-Request PDUs."],
28=>["snmpOutGetResponses","The total number of SNMP Get-Response PDUs."],
29=>["snmpOutTraps","The total number of SNMP Trap PDUs."],
30=>["snmpEnableAuthenTraps","Indicates whether the SNMP Agent process is permitted to generate authentication-failure traps.
enabled (1), disabled (2)"]
];
foreach ($data as $n => $i) {
    $oid = ".1.3.6.1.2.1.11.$n.0";
    echo "<tr>";
    echo "<td>$n</td>";
    echo "<td>$oid</td>";
    echo "<td>{$i[0]}</td>";
    echo "<td>{$i[1]}</td>";
    echo "<td>" . snmp2_get($ip, "public", $oid) . "</td>";
    echo "</tr>";
}
?>
</table>
</div>
<div class="section">
<div class="section-title">Method 2 : snmp2_walk()</div>
<table>
<tr>
    <th>Number</th>
    <th>Name</th>
    <th>Description</th>
    <th>Value</th>
</tr>
<?php
$walk = snmp2_walk($ip, "public", ".1.3.6.1.2.1.11");
$k = array_keys($data);
foreach ($walk as $i => $value) {
    $x = $k[$i];
    echo "<tr>";
    echo "<td>$x</td>";
    echo "<td>{$data[$x][0]}</td>";
    echo "<td>{$data[$x][1]}</td>";
    echo "<td>$value</td>";
    echo "</tr>";
}
?>
</table>
</div>
</div>
<?php $page =3; require_once 'footer.php'; ?>